# A configuration file for our Quality Infrastructure builds: https://wiki.gpii.net/w/Quality_Infrastructure
email: tony@raisingthefloor.org
env_runtime: linux-desktop

apps:
  - app_name: gpii-pouchdb
    git_repository: https://github.com/the-t-in-rtf/gpii-pouchdb.git
    git_branch: GPII-1815
    software_stack: nodejs
    software_stack_version: lts
    folder:
      dest: /app/gpii-pouchdb
    run_in: fedora
    deploy: false
    setup:
      - yarn install
    test_cmds:
      - TMPDIR=/var/tmp yarn test
